version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: chat_bot_uir
      POSTGRES_PASSWORD: mvxu9eRqVlIYsmU8aa
      POSTGRES_DB: db_bot_uir
    ports:
     - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
